export { default as AboutPage } from './AboutPage/AboutPage'
export { default as ErrorPage } from './ErrorPage/ErrorPage'
export { default as HomePage } from './HomePage/HomePage'
export { default as LoginPage } from './LoginPage/LoginPage'
export { default as RegisterPage } from './RegisterPage/RegisterPage'
export { default as SearchPage } from './SearchPage/SearchPage'